# taken from https://github.com/joerick/cibuildwheel-autopypi-example/blob/master/appveyor.yml
# you need to create the API key TWIN_PASSWORD in here https://ci.appveyor.com/api-keys
image: ubuntu
platform:
  - x64
environment:
  global:
    CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*
    CIBW_BEFORE_BUILD: pip install cython && pip install numpy
    TWINE_USERNAME: __token__
    # Note: TWINE_PASSWORD is set to an API token in Appveyor settings
 
build_script:
  - sudo pip install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
