# taken from https://github.com/joerick/cibuildwheel-autopypi-example/blob/master/appveyor.yml
# you need to create the API key TWIN_PASSWORD in here https://ci.appveyor.com/api-keys

# Skip Python 2.7 and Python 3.5


environment:
  TWINE_USERNAME: __token__
  # Note: TWINE_PASSWORD is set to an API token in Appveyor settings
  global:
    CIBW_SKIP: cp27-* cp35-*
build_script:
  - pip install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
