# taken from https://github.com/joerick/cibuildwheel-autopypi-example/blob/master/appveyor.yml
# you need to create the API key TWIN_PASSWORD in here https://ci.appveyor.com/api-keys
image: 
    - ubuntu
    - Visual Studio 2019
platform:
  - x64
environment:
  global:
    CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* cp37-* cp38-* *-win32
    CIBW_BEFORE_BUILD: pip install cython && pip install numpy
    CIBW_BEFORE_BUILD_LINUX: pip install cython && pip install numpy
    TWINE_USERNAME: __token__
    CIBW_PLATFORM: linux
    # Note: TWINE_PASSWORD is set to an API token in Appveyor settings
 
build_script:
  - sh: sudo pip install cibuildwheel==1.0.0 
  - cmd: pip install cibuildwheel==1.0.0
  - sh: cibuildwheel --output-dir wheelhouse --platform linux
  - cmd: cibuildwheel --output-dir wheelhouse
  - sh: sudo pip install twine
  - cmd: pip install twine
  - python -m twine upload wheelhouse/*.whl --skip-existing --repository-url  https://test.pypi.org/legacy/
   
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
