name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish python wheel to testPyPI and PyPI
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install setuptools wheel 
        python setup.py sdist bdist_wheel
    - name: Build and publish to testPyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      repository_url: https://test.pypi.org/legacy/
      with:
        user: ${{ secrets.test_pypi_username }} 
        password: ${{ secrets.test_pypi_password }}
    - name: Build and publish to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.pypi_username }} 
        password: ${{ secrets.pypi_password }}
      
    
