name: Upload Python Package

on: [push]

jobs:
  deploy:
    runs-on: windows
    steps:
    - uses: actions/checkout@v2
    - name: Publish python wheel to testPyPI and PyPI
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install setuptools wheel 
        pip install -r requirements.txt
        python setup.py sdist bdist_wheel
    - name: Build and publish to testPyPI      
      uses: pypa/gh-action-pypi-publish@master      
      with:
        repository_url: https://test.pypi.org/legacy/ 
        password: ${{ secrets.test_pypi_password }}
    - name: Build and publish to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
      
    
